baseURL = "https://lazar-jelic-am01.netlify.app"
title = "home"
theme = "hugo-coder"

[params]
author = "lazar jelic"
avatarURL = "images/avatar.jpeg"
commit = "https://github.com/luizdepra/hugo-coder/tree"
description = "lazar jelic's portfolio"
footerContent = "made with <3"
info = ["an lbs mam 2022 student", "interested in quantitative asset management"]
colorScheme = "auto"
hideColorSchemeToggle = false

[[params.social]]
name = "cv"
icon = "fa fa-id-card"
url = "docs/cv.pdf"

[[params.social]]
name = "website"
icon = "fa fa-globe"
url = "https://lazarjelic.com"

[[params.social]]
name = "github"
icon = "fa fa-github"
url = "https://github.com/jelic98"

[[params.social]]
name = "linkedin"
icon = "fa fa-linkedin"
url = "https://www.linkedin.com/in/jelic98"

[[languages.en.menu.main]]
name = "contact"
url = "contact"

[[languages.en.menu.main]]
name = "projects"
url = "projects"
