baseURL: https://lazar-jelic-am01.netlify.app
title: Lazar Jelic's portfolio
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Lazar Jelic
  avatarURL: https://media-exp1.licdn.com/dms/image/C4E03AQGFuTX6XNEaLg/profile-displayphoto-shrink_200_200/0/1610072379513?e=1635984000&v=beta&t=_Pml_4AUIk5Wztu_pnJxCyFqw9rq1hboxUfkrDVanR0
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree
  csp:
    childsrc: '''self'''
    connectsrc:
      - '''self'''
      - https://www.google-analytics.com
    fontsrc:
      - '''self'''
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net
    formaction: '''self'''
    framesrc: '''self'''
    imgsrc: '''self'''
    objectsrc: '''none'''
    prefetchsrc: '''self'''
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://www.google-analytics.com
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://fonts.googleapis.com
      - https://cdn.jsdelivr.net
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: September 4, 2021
  description: Lazar Jelic's portfolio
  enableTwemoji: no
  footerContent: Made with <3
  hideColorSchemeToggle: no
  hideCopyright: no
  hideCredits: no
  hideFooter: no
  info:
    - MAM 2022
  keywords: blog, portfolio, personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2021
  social:
    - icon: fa fa-github
      name: Github
      url: https://github.com/jelic98
      weight: 1
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/jelic98
      weight: 4
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: Projects
          url: projects/
        - name: Contact me
          url: contact/
